version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: staff
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 825356
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: staff-spring-app
    container_name: spring-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/staff
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 825356
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
