version: '3'

services:
  angular-app:
    build: .
    image: aifox-ui-image
    container_name: airfox-ui-container
    ports:
      - "4200:4200"  # Map container port 80 to host port 4200
    volumes:
      - .:/app  # Mount the current directory to /app in the container

    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    external: true